// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.ML;
using StocksAndBondsML.Model;

namespace StocksAndBondsML.Model
{
    public class ConsumeModel
    {
        // For more info on consuming ML.NET models, visit https://aka.ms/model-builder-consume
        // Method for consuming model in your app
        public static ModelOutput Predict(ModelInput input)
        {

            // Create new MLContext
            MLContext mlContext = new MLContext();

            // Load model & create prediction engine
            // Currently in: C:\Users\Elsa\Source\Repos\StocksAndBonds\StocksAndBondsML.ConsoleApp\bin\Debug\netcoreapp2.1
            string modelPath = @"C:\Users\Elsa\AppData\Local\Temp\MLVSTools\StocksAndBondsML\StocksAndBondsML.Model\MLModel.zip";
            ITransformer mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);

            // Use model to make prediction on input data
            ModelOutput result = predEngine.Predict(input);
            return result;
        }
    }
}
