// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace StocksAndBondsML.Model
{
    public class ModelInput
    {
        [ColumnName("security"), LoadColumn(0)]
        public string Security { get; set; }


        [ColumnName("year"), LoadColumn(1)]
        public float Year { get; set; }


        [ColumnName("price"), LoadColumn(2)]
        public float Price { get; set; }


        [ColumnName("delta"), LoadColumn(3)]
        public float Delta { get; set; }


        [ColumnName("isSplit"), LoadColumn(4)]
        public bool IsSplit { get; set; }


        [ColumnName("yield"), LoadColumn(5)]
        public float Yield { get; set; }


        [ColumnName("return"), LoadColumn(6)]
        public float Return { get; set; }


        [ColumnName("rateofreturn"), LoadColumn(7)]
        public float Rateofreturn { get; set; }


    }
}
